import { STATUS } from './statuses';

export const TOTAL_POSSIBLE_COMBOS = 1326;

export const HAND_TYPE = {
  pair: 'pair',
  suited: 'suited',
  unsuited: 'unsuited',
} as const;

// prettier-ignore
export const HANDS = [
  'AA', 'AKs', 'AQs', 'AJs', 'ATs', 'A9s', 'A8s', 'A7s', 'A6s', 'A5s','A4s', 'A3s', 'A2s',
  'AK', 'KK', 'KQs', 'KJs', 'KTs', 'K9s', 'K8s', 'K7s', 'K6s', 'K5s','K4s', 'K3s', 'K2s',
  'AQ', 'KQ','QQ', 'QJs', 'QTs', 'Q9s', 'Q8s', 'Q7s', 'Q6s', 'Q5s','Q4s', 'Q3s', 'Q2s',
  'AJ', 'KJ','QJ', 'JJ', 'JTs', 'J9s', 'J8s', 'J7s', 'J6s', 'J5s','J4s', 'J3s', 'J2s',
  'AT', 'KT','QT', 'JT', 'TT', 'T9s', 'T8s', 'T7s', 'T6s', 'T5s','T4s', 'T3s', 'T2s',
  'A9', 'K9','Q9', 'J9', 'T9', '99', '98s', '97s', '96s', '95s','94s', '93s', '92s',
  'A8', 'K8','Q8', 'J8', 'T8', '98', '88', '87s', '86s', '85s','84s', '83s', '82s',
  'A7', 'K7','Q7', 'J7', 'T7', '97', '87', '77', '76s', '75s','74s', '73s', '72s',
  'A6', 'K6','Q6', 'J6', 'T6', '96', '86', '76', '66', '65s','64s', '63s', '62s',
  'A5', 'K5','Q5', 'J5', 'T5', '95', '85', '75', '65', '55','54s', '53s', '52s',
  'A4', 'K4','Q4', 'J4', 'T4', '94', '84', '74', '64', '54','44', '43s', '42s',
  'A3', 'K3','Q3', 'J3', 'T3', '93', '83', '73', '63', '53','43', '33', '32s',
  'A2', 'K2','Q2', 'J2', 'T2', '92', '82', '72', '62', '52','42', '32', '22',
] as const;

export const PAIRS = ['AA', 'KK', 'QQ', 'JJ', 'TT', '99', '88', '77', '66', '55', '44', '33', '22'] as const;

export const SUITED_CONNECTORS = [
  'AKs',
  'KQs',
  'QJs',
  'JTs',
  'T9s',
  '98s',
  '87s',
  '76s',
  '65s',
  '54s',
  '43s',
  '32s',
] as const;

export const BROADWAY = [
  'AA',
  'AKs',
  'AQs',
  'AJs',
  'ATs',
  'AK',
  'KK',
  'KQs',
  'KJs',
  'KTs',
  'AQ',
  'KQ',
  'QQ',
  'QJs',
  'QTs',
  'AJ',
  'KJ',
  'QJ',
  'JJ',
  'JTs',
  'AT',
  'KT',
  'QT',
  'JT',
  'TT',
] as const;

export const DEFAULT_HAND_STATUS_MAP = {
  AA: STATUS.no,
  AKs: STATUS.no,
  AQs: STATUS.no,
  AJs: STATUS.no,
  ATs: STATUS.no,
  A9s: STATUS.no,
  A8s: STATUS.no,
  A7s: STATUS.no,
  A6s: STATUS.no,
  A5s: STATUS.no,
  A4s: STATUS.no,
  A3s: STATUS.no,
  A2s: STATUS.no,
  AK: STATUS.no,
  KK: STATUS.no,
  KQs: STATUS.no,
  KJs: STATUS.no,
  KTs: STATUS.no,
  K9s: STATUS.no,
  K8s: STATUS.no,
  K7s: STATUS.no,
  K6s: STATUS.no,
  K5s: STATUS.no,
  K4s: STATUS.no,
  K3s: STATUS.no,
  K2s: STATUS.no,
  AQ: STATUS.no,
  KQ: STATUS.no,
  QQ: STATUS.no,
  QJs: STATUS.no,
  QTs: STATUS.no,
  Q9s: STATUS.no,
  Q8s: STATUS.no,
  Q7s: STATUS.no,
  Q6s: STATUS.no,
  Q5s: STATUS.no,
  Q4s: STATUS.no,
  Q3s: STATUS.no,
  Q2s: STATUS.no,
  AJ: STATUS.no,
  KJ: STATUS.no,
  QJ: STATUS.no,
  JJ: STATUS.no,
  JTs: STATUS.no,
  J9s: STATUS.no,
  J8s: STATUS.no,
  J7s: STATUS.no,
  J6s: STATUS.no,
  J5s: STATUS.no,
  J4s: STATUS.no,
  J3s: STATUS.no,
  J2s: STATUS.no,
  AT: STATUS.no,
  KT: STATUS.no,
  QT: STATUS.no,
  JT: STATUS.no,
  TT: STATUS.no,
  T9s: STATUS.no,
  T8s: STATUS.no,
  T7s: STATUS.no,
  T6s: STATUS.no,
  T5s: STATUS.no,
  T4s: STATUS.no,
  T3s: STATUS.no,
  T2s: STATUS.no,
  A9: STATUS.no,
  K9: STATUS.no,
  Q9: STATUS.no,
  J9: STATUS.no,
  T9: STATUS.no,
  '99': STATUS.no,
  '98s': STATUS.no,
  '97s': STATUS.no,
  '96s': STATUS.no,
  '95s': STATUS.no,
  '94s': STATUS.no,
  '93s': STATUS.no,
  '92s': STATUS.no,
  A8: STATUS.no,
  K8: STATUS.no,
  Q8: STATUS.no,
  J8: STATUS.no,
  T8: STATUS.no,
  '98': STATUS.no,
  '88': STATUS.no,
  '87s': STATUS.no,
  '86s': STATUS.no,
  '85s': STATUS.no,
  '84s': STATUS.no,
  '83s': STATUS.no,
  '82s': STATUS.no,
  A7: STATUS.no,
  K7: STATUS.no,
  Q7: STATUS.no,
  J7: STATUS.no,
  T7: STATUS.no,
  '97': STATUS.no,
  '87': STATUS.no,
  '77': STATUS.no,
  '76s': STATUS.no,
  '75s': STATUS.no,
  '74s': STATUS.no,
  '73s': STATUS.no,
  '72s': STATUS.no,
  A6: STATUS.no,
  K6: STATUS.no,
  Q6: STATUS.no,
  J6: STATUS.no,
  T6: STATUS.no,
  '96': STATUS.no,
  '86': STATUS.no,
  '76': STATUS.no,
  '66': STATUS.no,
  '65s': STATUS.no,
  '64s': STATUS.no,
  '63s': STATUS.no,
  '62s': STATUS.no,
  A5: STATUS.no,
  K5: STATUS.no,
  Q5: STATUS.no,
  J5: STATUS.no,
  T5: STATUS.no,
  '95': STATUS.no,
  '85': STATUS.no,
  '75': STATUS.no,
  '65': STATUS.no,
  '55': STATUS.no,
  '54s': STATUS.no,
  '53s': STATUS.no,
  '52s': STATUS.no,
  A4: STATUS.no,
  K4: STATUS.no,
  Q4: STATUS.no,
  J4: STATUS.no,
  T4: STATUS.no,
  '94': STATUS.no,
  '84': STATUS.no,
  '74': STATUS.no,
  '64': STATUS.no,
  '54': STATUS.no,
  '44': STATUS.no,
  '43s': STATUS.no,
  '42s': STATUS.no,
  A3: STATUS.no,
  K3: STATUS.no,
  Q3: STATUS.no,
  J3: STATUS.no,
  T3: STATUS.no,
  '93': STATUS.no,
  '83': STATUS.no,
  '73': STATUS.no,
  '63': STATUS.no,
  '53': STATUS.no,
  '43': STATUS.no,
  '33': STATUS.no,
  '32s': STATUS.no,
  A2: STATUS.no,
  K2: STATUS.no,
  Q2: STATUS.no,
  J2: STATUS.no,
  T2: STATUS.no,
  '92': STATUS.no,
  '82': STATUS.no,
  '72': STATUS.no,
  '62': STATUS.no,
  '52': STATUS.no,
  '42': STATUS.no,
  '32': STATUS.no,
  '22': STATUS.no,
};
